import { Post } from '@prisma/client'
import Head from 'next/head'
import { FormEvent, useCallback, useEffect, useState } from 'react'

export default function Home() {
  const [posts, setPosts] = useState<Post[]>([])
  const [body, setBody] = useState('')

  const initialize = useCallback(async () => {
    const response = await fetch('/api/get')
    const data = (await response.json()) as { posts: Post[] }
    setPosts(data.posts)
  }, [])

  useEffect(() => {
    initialize()
  }, [])

  const onSubmit = useCallback(
    async (e: FormEvent<HTMLFormElement>) => {
      e.preventDefault()
      const response = await fetch('/api/post', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ body }),
      })
      const data = (await response.json()) as { posts: Post[] }
      setPosts(data.posts)
      setBody('')
    },
    [body]
  )

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <form onSubmit={onSubmit}>
          <div>
            <textarea
              name="body"
              value={body}
              onChange={(e) => setBody(e.target.value)}
            ></textarea>
          </div>
          <div>
            <button type="submit">Submit</button>
          </div>
        </form>
        {posts.map((post) => (
          <div key={post.id}>
            <p style={{ marginBottom: '1rem' }}>{post.body}</p>
          </div>
        ))}
      </main>
    </div>
  )
}
